### ISSUE TITLE
Feature Request: Syntax highlighting for fenced code blocks

### ISSUE THREAD

**Issue by jbaum98** [joshuacaron/markdown#1]
``` ruby
class Foo
    def bar
        return 4 if correct?
    end
end
```

```ruby
class Foo
    def bar
        return 4 if correct?
    end
end
```

**Comment by joshuacaron** [comment]
Hi, thanks for your feedback. I will probably use highlight.js so that it will autodetect the language and match the standard Markdown syntax for code blocks, i.e. there will be no change on the user side, and you can enter code blocks as you already would, but code will start showing up highlighted.

I will comment again when I have updated it, but it should be within the next day or two.

**Comment by joshuacaron** [comment]
I added syntax highlighting inside code blocks. It will automatically detect which language you use. You can enable this setting in the settings pane. Pressing tab now inputs 4 spaces as well so that typing code is a lot easier. The new code should be live on the Chrome Webstore soon. Thanks again for your input.
